### PR TITLE
login demo for backend quiz

### PR DESCRIPTION
**Pull request by xavierchow**
@makara 
I don't know whether this PR is what you expected, any comment is appreciated.
Next I will try to learn and grasp the Go language from scratch.

### CODE REVIEW

**Comment by makara** [comment]
Yes it is. Can you also list what 3rd-party libs you are using and why?

Regarding to the Go thing, it's about how you solve it more than how you code it. Make use of some libs if you can (and again explain why).

**Comment by xavierchow** [comment]
> Can you also list what 3rd-party libs you are using and why?

The npm modules I used are as follows,
```
  "devDependencies": {
    "mocha": "^2.3.0",
    "supertest": "^1.1.0"
  },
  "dependencies": {
    "body-parser": "^1.13.3",
    "connect-flash": "^0.1.1",
    "express": "^4.13.3",
    "express-session": "^1.11.3",
    "jade": "^1.11.0",
    "lodash": "^3.10.1",
    "passport": "^0.3.0",
    "passport-local": "^1.0.0"
  }
```
The significant one is [passport](https://github.com/jaredhanson/passport), I used it for tow reasons:
* It's a modular/flexible authentication middlewire for express-based web application.
* Although in the demo I use local strategy, it's also very easy to switch to other authenticate strategies such as basic/oauth/openID etc..

**Comment by makara** [comment]
@xavierchow How's going with the Golang app? Let me know if you are not comfortable with it. We can try something else.

**Comment by xavierchow** [comment]
@makara 
Thanks for your consideration. It's almost done. I will make a PR later.

**Comment by makara** [comment]
Thanks. Been a long time isn't it. Closing.

**Pull request closed without merging**
