### PR TITLE
done

### PR DESCRIPTION
**Pull request by MalavitaC**
by 蔡忞豪

### CODE REVIEW

**Comment by MiffyLiye** [comment]
Hello, I'm Tao from Wiredcraft, I'm going to review the code and ask some questions.

1. In typical RESTful API design, what should query API respond when user doesn't exist?
2. `dob` field is not saved in create API, do you have API document about how to save `dob` field in user model?
3.  the unit test doesn't cover CRUD of users, what do you think should be covered in unit test, and how can different style of unit test help our development?

**Comment by xavierchow** [comment]
@MalavitaC any updates? ^

**Comment by MalavitaC** [comment]
I worked overtime last weekend, so I didn't update the code.

**Comment by xavierchow** [comment]
thank you all, closing this PR.

**Comment by MalavitaC** [comment]
Okay, I was just about to commit code.

**Pull request closed without merging**
